version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-docgen}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docgen}
      POSTGRES_DB: ${POSTGRES_DB:-docgen}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://docgen:docgen@db:5432/docgen}
    volumes:
      - ./backend/storage:/app/backend/storage
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  db_data: